image: gbaulieu/ubuntu-root:v2

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script: 
  script: 
    - sed -i s/CMSSW_ENABLED=true/CMSSW_ENABLED=false/ Makefile
    - export ROOTSYS=/opt/root/
    - export PATH=/opt/root/bin/:$PATH
    - export LD_LIBRARY_PATH=/opt/root/lib/:$LD_LIBRARY_PATH
    - make
  artifacts:
    paths:
      - AMSimulation
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - export ROOTSYS=/opt/root/
    - export PATH=/opt/root/bin/:$PATH
    - export LD_LIBRARY_PATH=/opt/root/lib/:$LD_LIBRARY_PATH
    - ./AMSimulation --help
